### ISSUE TITLE
Exordium and Modmenu crash game at launch

### ISSUE THREAD

**Issue by K4sum1** [Chocohead/Not-So-New#11]
Exordium crash log

https://mclo.gs/ebgcSj3

Modmenu crash log

https://mclo.gs/HbqNImR

**Comment by K4sum1** [comment]
Modmenu 9.0.0 still crashes, but 9.2.0 beta 2 seems to work fine. Exordium got fixed with a commit.

Guess bug with Modmenu if updating it fixed it.

**Comment by Chocohead** [comment]
ModMenu 9.0.0 has been fixed with c87a19d, as a missing extension of a3adbe3
