### ISSUE TITLE
Iris 1.6.11 crashes at main menu

### ISSUE THREAD

**Issue by K4sum1** [Chocohead/Not-So-New#17]
1.18.2 is the newest I can get running on XP unless you make a mod to backport 1.19+ to LWJGL 3.2.2 as well. So I've been testing what in my mod list breaks it. I was too busy to upload logs, but since you replied to all my stuff, I figure I should do it now.

To get it to crash the fastest, I just move the mouse over the main menu options.

https://mclo.gs/Z1wvrDw

**Comment by Chocohead** [comment]
If you swap out the LWJGL 3.3 `lwjgl_stb.dll` with the 3.2 one (and make sure it doesn't get replaced when you next start the game, I marked mine as read-only), but keep the 3.3 `lwjgl_stb.jar`, the newer Minecraft versions will boot/work on XP:

![2002-01-01 06_00_39-Greenshot](https://github.com/Chocohead/Not-So-New/assets/4021725/6f17572c-2e9e-4817-a01c-cf3ab4ba0cc8)

As for the actual crash, doesn't look too difficult to solve...

**Comment by K4sum1** [comment]
Hmm, for me the 3.3 OpenAL was being funny, and I replaced it with the 3.2 OpenAL, and got a 0xc000005 at launch. I guess this would be the second piece. I'll have to try this, thanks.

**Comment by Chocohead** [comment]
I had had issues with OpenAL too, but I'd not installed the Nvidia driver properly was getting crashes about not having any OpenAL context at all.  I might have replaced the OpenAL version on the way to trying to fix that, don't remember now. `0xc000005` is definitely the native crash code I got from all the 3.3 versions of `stb` though.

**Comment by K4sum1** [comment]
How do you have 8u332 on XP? Stock can only run up to 8u241? I'm wanting to do this stock.

I tried 1.19.4 and it crashes with replaced OpenAL and stb. I'll try 1.20.4 when I'm not feeling lazy.

**Comment by K4sum1** [comment]
For this, I made a new release named funny-1.20.4, and replaced the references to OpenAL and stb with those from 3.2 in the .json, then made a funny-fabric release that pointed to funny-1.20.4. Not sure if this would work or not. Game crashes for me though.

https://mclo.gs/gKd54fz

**Comment by K4sum1** [comment]
I love you

![DSC_0045](https://github.com/Chocohead/Not-So-New/assets/77039240/9dd0ee44-0515-437a-b505-5c139527a9b3)

**Comment by K4sum1** [comment]
So it appears the Iris bug happens on 1.20.4 as well. I didn't notice it in previous testing.

**Comment by Chocohead** [comment]
Wonderful to see you got it working :)

> How do you have 8u332 on XP? Stock can only run up to 8u241? I'm wanting to do this stock.

I'm using (stock) 32-bit XP SP3, using the last ojdkbuild of Java from [here](https://github.com/ojdkbuild/ojdkbuild/releases/java-1.8.0-openjdk-1.8.0.332-1.b09-x86). I'm not sure if there's newer versions of Java 8 out there which still work on XP; I doubt there's many people trying to find out either way.

**Comment by K4sum1** [comment]
Might not be fixable here. If I downgrade those to run on XP, in ModernFix, mixin.perf.faster_texture_stitching fails to load resources causing MC to hang on the loading screen. If I set to false, it's fine.

**Comment by Chocohead** [comment]
> Might not be fixable here. If I downgrade those to run on XP, in ModernFix, mixin.perf.faster_texture_stitching fails to load resources causing MC to hang on the loading screen. If I set to false, it's fine.
> 
> https://mclo.gs/Yvh0SE0

This is a consequence of 3.2 STB not quite being the same as 3.3 STB. Specifically the `stbrp_rect` struct is aligned differently. ModernFix's use of STB for producing the texture atlas falls foul of this, so thinks it has failed when it probably hasn't. This might be fixable with mixins... but I'll not promise anything as I suspect it'll be a nuisance.

> Also got this crash on exit, idk if related.
> 
> https://mclo.gs/HrD0ZEt

`ig4icd64` is the Intel OpenGL driver, can't be sure why it's unhappy or what it's unhappy about.

> As for the actual crash, looks quite curious so hopefully isn't too difficult to solve...

Turns out it's a bug in Mixin: FabricMC/Mixin#146

**Comment by K4sum1** [comment]
> This is a consequence of 3.2 STB not quite being the same as 3.3 STB. Specifically the stbrp_rect struct is aligned differently. ModernFix's use of STB for producing the texture atlas falls foul of this, so thinks it has failed when it probably hasn't. This might be fixable with mixins... but I'll not promise anything as I suspect it'll be a nuisance.

Wonder if it could be forked and patched to work with 3.2 STB. Not that important to me though.

> `ig4icd64` is the Intel OpenGL driver, can't be sure why it's unhappy or what it's unhappy about.

It's known to be notoriously shit, had to use ForceGL20 for the game to work. Probably that I guess.

> Turns out it's a bug in Mixin: [FabricMC/Mixin#146](https://github.com/FabricMC/Mixin/issues/146)

Hope it gets fixed soon.

Also I made a how to post on my forum for getting newer versions working.

https://board.eclipse.cx/viewtopic.php?t=707

**Comment by K4sum1** [comment]
The Mixin thing got fixed a while back. How should I test this? Does it need Not-So-New update, Iris update, or something else?

**Comment by K4sum1** [comment]
So Mixin is part of the Fabric Loader, and I assume some 0.16.x has the fixed version. However 0.16.0+ crashes at launch with NotSoNew.

https://mclo.gs/aowh5ML
