### ISSUE TITLE
Half of the FPS as compared to regular Java 17 in 1.20.4

### ISSUE THREAD

**Issue by K4sum1** [Chocohead/Not-So-New#21]
With my mod list, I get 214 FPS in regular 1.20.4 with Java 17. With Java 8 and NotSoNew, I get 106 FPS. It seems to halve my FPS.

~~It's basically Fabulously Optimized with some of the extra mods removed.~~

**Comment by Chocohead** [comment]
I had noticed that there was a performance difference, even once things have settled after entering a world, but it's quite hard to work out what's contributing what. Newer Java versions are inherently faster than Java 8, the GC has improved and there are more Java methods replaced with native ones at runtime on top.
Converting new idiomatic bytecode might also not make idiomatic Java 8 bytecode; concatenating strings together is something which Java 8 is quite fickle about for example, if it recognises that's what you're doing the JIT can make it quicker, but the conditions for it to recognise that are unclear. It's this fickleness which made them [change the compiler behaviour](https://bugs.openjdk.org/browse/JDK-8085796) in Java 9.

I'm certainly not trying to make it slower, there'd be no point, but you'd need to profile the game to see what is disproportionately slower. Unless you want to [sell your soul to Oracle](https://docs.oracle.com/en/java/java-components/enterprise-performance-pack/epp-user-guide/overview.html).

**Comment by K4sum1** [comment]
I found with 1.16.5 that Java 8 was faster than 11 and 17. I guess newer versions take better advantage of newer Java releases.
