### ISSUE TITLE
FerriteCore crashes when using Not So New

### ISSUE THREAD

**Issue by TheMajorTechie** [Chocohead/Not-So-New#26]
Attached is the log file when attempting to launch with FerriteCore, FabricAPI, and Not So New. The main system I'm attempting to test things with is a 32 bit Intel Core Duo running Windows XP, but for ease of filing this report I have recreated the instance on my primary PC.

[notsonewcrashlog.log](https://github.com/user-attachments/files/18134476/notsonewcrashlog.log)

**Comment by Chocohead** [comment]
Looks like its mixin plugin is dynamically loading a class by name [here](https://github.com/malte0811/FerriteCore/blob/3b41f0500a5d5196115f83dab4c48a76d2f60204/Common/src/main/java/malte0811/ferritecore/util/Constants.java#L12), hopefully won't take too many adjustments to [`TypeSpectator`](https://github.com/Chocohead/Not-So-New/blob/master/src/com/chocohead/nsn/TypeSpectator.java)

**Comment by TheMajorTechie** [comment]
Sweet, thanks for looking into it!
