### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by K4sum1** [Chocohead/Not-So-New#6]
I tried 1.17, and this is what I get when trying to run it.

>ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
>ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
>[17:53:48] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.14.21
>[17:53:48] [main/INFO]: Dependencies overridden for minecraft, fabric, antighost, advancementinfo, hydrogen, colormatic
>[17:53:48] [main/INFO]: Loading 5 mods:
>	- fabricloader 0.14.21
>	- java 8
>	- minecraft 1.17.1
>	- nsn 5.2
>	   \-- mm 2.3
>ERROR StatusLogger Unrecognized format specifier [d]
>ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [thread]
>ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [level]
>ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [logger]
>ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [msg]
>ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [n]
>ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [d]
>ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [thread]
>ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [level]
>ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [logger]
>ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [msg]
>ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
>ERROR StatusLogger Unrecognized format specifier [n]
>ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
>ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
>[17:53:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/G:/1Misc%20Stuff%20for%20Install/minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
>[17:53:49] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>	at net.fabricmc.loader.impl.launch.FabricLauncherBase.finishMixinBootstrapping(FabricLauncherBase.java:137) ~[fabric-loader-0.14.21.jar:?]
>	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.21.jar:?]
>	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
>	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
>Caused by: java.lang.reflect.InvocationTargetException
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_371]
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_371]
>	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_371]
>	at net.fabricmc.loader.impl.launch.FabricLauncherBase.finishMixinBootstrapping(FabricLauncherBase.java:134) ~[fabric-loader-0.14.21.jar:?]
>	... 3 more
>Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Duplicate key com.chocohead.nsn.Nester$1Member@1b4b3e0
>	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_371]
>	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_371]
>	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606) ~[?:1.8.0_371]
>	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_371]
>Caused by: java.lang.IllegalStateException: Duplicate key com.chocohead.nsn.Nester$1Member@1b4b3e0
>	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_371]
>	at java.util.HashMap.merge(HashMap.java:1255) ~[?:1.8.0_371]
>	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_371]
>	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_371]
>	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_371]
>	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_371]
>	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_371]
>	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_371]
>	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_371]
>	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_371]
>	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_371]
>	at com.chocohead.nsn.Nester.resolveNestSystem(Nester.java:309) ~[NotSoNew-v5.2.jar:?]
>	at com.chocohead.nsn.Nester.access$000(Nester.java:47) ~[NotSoNew-v5.2.jar:?]
>	at com.chocohead.nsn.Nester$ScanResult.lambda$calculateNests$0(Nester.java:82) ~[NotSoNew-v5.2.jar:?]
>	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_371]
>	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_371]
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_371]

**Comment by Chocohead** [comment]
I've not tested 1.17 in a long time, must have broken something along the way. I'll see if I can work out what's wrong
