### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by 4194304** [Chocohead/Not-So-New#7]
Are you still working on this or is it abandoned?

**Comment by Chocohead** [comment]
It gets worked on periodically; I didn't think there were many people interested, let alone using it. As it happens I have been looking into what 1.20.1 needs as part of a semi-related project this weekend.

**Comment by K4sum1** [comment]
@Chocohead I'm interested in this again and would love to see a release that works with 1.20.4. It seems to run a lot better than previous versions. I'd love to see what happens with Java 8.

**Comment by Chocohead** [comment]
The newest Not So New 5.22 release supports all 1.20 versions (released so far at least). Let me know how you get on with it.
